[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
action_example = "BDwf8Mx2Cji2rNWCQ1atRsBMrDvcX485USgg7TVD3UjK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
